# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '+m:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' menu select=long-list select=1
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install


if [ -d $HOME/.local/bin ]; then
	export PATH=$HOME/.local/bin:$PATH
fi

if [ -f ~/.zsh_local_init ]; then
    source ~/.zsh_local_init
fi

if [ ! -f ~/.local/bin/antigen.zsh ]; then
	# Antigen: https://github.com/zsh-users/antigen
	ANTIGEN="$HOME/.local/bin/antigen.zsh"

	# Install antigen.zsh if not exist
	if [ ! -f "$ANTIGEN" ]; then
		echo "Installing antigen ..."
		[ ! -d "$HOME/.local" ] && mkdir -p "$HOME/.local" 2> /dev/null
		[ ! -d "$HOME/.local/bin" ] && mkdir -p "$HOME/.local/bin" 2> /dev/null
		[ ! -f "$HOME/.z" ] && touch "$HOME/.z"
		URL="http://git.io/antigen"
		TMPFILE="/tmp/antigen.zsh"
		if [ -x "$(which curl)" ]; then
			curl -L "$URL" -o "$TMPFILE" 
		elif [ -x "$(which wget)" ]; then
			wget "$URL" -O "$TMPFILE" 
		else
			echo "ERROR: please install curl or wget before installation !!"
			exit
		fi
		if [ ! $? -eq 0 ]; then
			echo ""
			echo "ERROR: downloading antigen.zsh ($URL) failed !!"
			exit
		fi;
		echo "move $TMPFILE to $ANTIGEN"
		mv "$TMPFILE" "$ANTIGEN"
	fi
fi
source ~/.local/bin/antigen.zsh
antigen init $HOME/.antigenrc

if [ -f ~/.zsh_env ]; then
    source ~/.zsh_env
fi

if [ -f ~/.fzf.zsh ]; then
	source ~/.fzf.zsh
fi


if [ -f ~/.zsh_local ]; then
    source ~/.zsh_local
fi
