# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '+m:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' menu select=long-list select=1
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install


if [ -d ~/.local/bin ]; then
	export PATH=$HOME/.local/bin:$PATH
fi

if [ -f ~/.zsh_local_init ]; then
    source ~/.zsh_local_init
fi

if [ -f ~/.local/bin/antigen.zsh ]; then
	source ~/.local/bin/antigen.zsh
	antigen init $HOME/.antigenrc
else
	source ~/.zsh_env
	source ~/.local/bin/antigen.zsh
	antigen init $HOME/.antigenrc
fi

if [ -f ~/.zsh_env ]; then
    source ~/.zsh_env
fi

if [ -f ~/.fzf.zsh ]; then
	source ~/.fzf.zsh
fi


if [ -f ~/.zsh_local ]; then
    source ~/.zsh_local
fi
